# Generated by Django 2.2 on 2019-06-15 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('concierge', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='location',
            name='url',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
